export const mockPackages = [
	{
		fecvue: '2023/01/16',
		itineravlo:
			'Salida 16 Enero Santiago-Rio de Janeiro vuelo SKY 620 Sale 05:05 Llega 09:15<br />\nRegreso 25 Enero Rio de Janeiro-Santiago vuelo SKY 621 Sale 10:05 Llega 14:55',
		pdBaggPersonal: '1',
		pdBaggMano: '0',
		pdBaggBodega: '1',
		diaDesfaseBloq: '0',
		fechaOutBloq: '1900/01/01',
		code: 'PD_BL23RIO01',
		image: 'https://online.panamericanaturismo.cl/public/img/programas/upl_PD_BL23RIO01.jpg',
		city: 'RIO JANEIRO',
		country: 'BRASIL',
		title: 'VERANO EN RIO DE JANEIRO',
		notes:
			'Incluye tasas de embarque USD 41, sujeto a cambio por parte de las autoridades locales.<br />\nServicios de traslados incluidos en servicio compartido. Consultar por precios en privado.<br />\nHabitaciones triples podrían estar compuestas de 2 camas dobles para compartir.',
		description: '',
		epigraph: '',
		coverage: [
			'Pasaje aéreo Santiago/Rio de Janeiro/Santiago vía Sky Airline. Vuelo directo.',
			'Incluye equipaje en bodega',
			'Traslado en servicio compartido aeropuerto / hotel',
			'Noches de alojamiento con desayuno',
			'Asistencia viajes de cortesía',
			'Traslado en servicio compartido hotel / aeropuerto',
			'Tasas de embarque',
			'',
		],
		amenities: {
			hotel: true,
			flight: true,
			transfer: true,
			insurance: true,
			excursion: false,
			food_plan_all: false,
		},
		amount: {
			USD: [{ total: 'US$635,00', _total: 635 }],
			CLP: [{ total: '$579.120', _total: 579120 }],
		},
	},
	{
		fecvue: '2023/01/23',
		itineravlo:
			'Salida 23 Enero Santiago-Rio de Janeiro vuelo SKY 620 Sale 05:05 Llega 09:15<br />\nRegreso 01 Febrero Rio de Janeiro-Santiago vuelo SKY 621 Sale 10:05 Llega 14:55',
		pdBaggPersonal: '1',
		pdBaggMano: '0',
		pdBaggBodega: '1',
		diaDesfaseBloq: '0',
		fechaOutBloq: '1900/01/01',
		code: 'PD_BL23RIO02',
		image: 'https://online.panamericanaturismo.cl/public/img/programas/upl_PD_BL23RIO02.jpg',
		city: 'RIO JANEIRO',
		country: 'BRASIL',
		title: 'VERANO EN RIO DE JANEIRO',
		notes:
			'Incluye tasas de embarque USD 41, sujeto a cambio por parte de las autoridades locales.<br />\nServicios de traslados incluidos en servicio compartido. Consultar por precios en privado.<br />\nHabitaciones triples podrían estar compuestas de 2 camas dobles para compartir.',
		description: '',
		epigraph: '',
		coverage: [
			'Pasaje aéreo Santiago/Rio de Janeiro/Santiago vía Sky Airline. Vuelo directo.',
			'Incluye equipaje en bodega',
			'Traslado en servicio compartido aeropuerto / hotel',
			'Noches de alojamiento con desayuno',
			'Asistencia viajes de cortesía',
			'Traslado en servicio compartido hotel / aeropuerto',
			'Tasas de embarque',
			'',
		],
		amenities: {
			hotel: true,
			flight: true,
			transfer: true,
			insurance: true,
			excursion: false,
			food_plan_all: true,
		},
		amount: {
			USD: [{ total: 'US$635,00', _total: 635 }],
			CLP: [{ total: '$579.120', _total: 579120 }],
		},
	},
	{
		fecvue: '2023/01/30',
		itineravlo:
			'Salida 30 Enero Santiago-Rio de Janeiro vuelo SKY 620 Sale 05:05 Llega 09:15<br />\nRegreso 08 Febrero Rio de Janeiro-Santiago vuelo SKY 621 Sale 10:05 Llega 14:55',
		pdBaggPersonal: '1',
		pdBaggMano: '0',
		pdBaggBodega: '1',
		diaDesfaseBloq: '0',
		fechaOutBloq: '1900/01/01',
		code: 'PD_BL23RIO03',
		image: 'https://online.panamericanaturismo.cl/public/img/programas/upl_PD_BL23RIO03.jpg',
		city: 'RIO JANEIRO',
		country: 'BRASIL',
		title: 'VERANO EN RIO DE JANEIRO',
		notes:
			'Incluye tasas de embarque USD 41, sujeto a cambio por parte de las autoridades locales.<br />\nServicios de traslados incluidos en servicio compartido. Consultar por precios en privado.<br />\nHabitaciones triples podrían estar compuestas de 2 camas dobles para compartir.',
		description: '',
		epigraph: '',
		coverage: [
			'Pasaje aéreo Santiago/Rio de Janeiro/Santiago vía Sky Airline. Vuelo directo.',
			'Incluye equipaje en bodega',
			'Traslado en servicio compartido aeropuerto / hotel',
			'Noches de alojamiento con desayuno',
			'Asistencia viajes de cortesía',
			'Traslado en servicio compartido hotel / aeropuerto',
			'Tasas de embarque',
			'',
		],
		amenities: {
			hotel: true,
			flight: true,
			transfer: true,
			insurance: true,
			excursion: false,
			food_plan_all: false,
		},
		amount: {
			USD: [{ total: 'US$635,00', _total: 635 }],
			CLP: [{ total: '$579.120', _total: 579120 }],
		},
	},
	{
		fecvue: '2023/02/06',
		itineravlo:
			'Salida 06 Febrero Santiago-Rio de Janeiro vuelo SKY 620 Sale 05:05 Llega 09:15<br />\nRegreso 15 Febrero Rio de Janeiro-Santiago vuelo SKY 621 Sale 10:05 Llega 14:55',
		pdBaggPersonal: '1',
		pdBaggMano: '0',
		pdBaggBodega: '1',
		diaDesfaseBloq: '0',
		fechaOutBloq: '1900/01/01',
		code: 'PD_BL23RIO04',
		image: 'https://online.panamericanaturismo.cl/public/img/programas/upl_PD_BL23RIO04.jpg',
		city: 'RIO JANEIRO',
		country: 'BRASIL',
		title: 'VERANO EN RIO DE JANEIRO',
		notes:
			'Incluye tasas de embarque USD 41, sujeto a cambio por parte de las autoridades locales.<br />\nServicios de traslados incluidos en servicio compartido. Consultar por precios en privado.<br />\nHabitaciones triples podrían estar compuestas de 2 camas dobles para compartir.',
		description: '',
		epigraph: '',
		coverage: [
			'Pasaje aéreo Santiago/Rio de Janeiro/Santiago vía Sky Airline. Vuelo directo.',
			'Incluye equipaje en bodega',
			'Traslado en servicio compartido aeropuerto / hotel',
			'Noches de alojamiento con desayuno',
			'Asistencia viajes de cortesía',
			'Traslado en servicio compartido hotel / aeropuerto',
			'Tasas de embarque',
			'',
		],
		amenities: {
			hotel: true,
			flight: true,
			transfer: true,
			insurance: true,
			excursion: false,
			food_plan_all: false,
		},
		amount: {
			USD: [{ total: 'US$635,00', _total: 635 }],
			CLP: [{ total: '$579.120', _total: 579120 }],
		},
	},
	{
		fecvue: '2023/02/13',
		itineravlo:
			'Salida 13 Febrero Santiago-Rio de Janeiro vuelo SKY 620 Sale 05:05 Llega 09:15<br />\nRegreso 22 Febrero Rio de Janeiro-Santiago vuelo SKY 621 Sale 10:05 Llega 14:55',
		pdBaggPersonal: '1',
		pdBaggMano: '0',
		pdBaggBodega: '1',
		diaDesfaseBloq: '0',
		fechaOutBloq: '1900/01/01',
		code: 'PD_BL23RIO05',
		image: 'https://online.panamericanaturismo.cl/public/img/programas/upl_PD_BL23RIO05.jpg',
		city: 'RIO JANEIRO',
		country: 'BRASIL',
		title: 'VERANO EN RIO DE JANEIRO',
		notes:
			'Incluye tasas de embarque USD 41, sujeto a cambio por parte de las autoridades locales.<br />\nServicios de traslados incluidos en servicio compartido. Consultar por precios en privado.<br />\nHabitaciones triples podrían estar compuestas de 2 camas dobles para compartir.',
		description: '',
		epigraph: '',
		coverage: [
			'Pasaje aéreo Santiago/Rio de Janeiro/Santiago vía Sky Airline. Vuelo directo.',
			'Incluye equipaje en bodega',
			'Traslado en servicio compartido aeropuerto / hotel',
			'Noches de alojamiento con desayuno',
			'Asistencia viajes de cortesía',
			'Traslado en servicio compartido hotel / aeropuerto',
			'Tasas de embarque',
			'',
		],
		amenities: {
			hotel: true,
			flight: true,
			transfer: true,
			insurance: true,
			excursion: false,
			food_plan_all: false,
		},
		amount: {
			USD: [{ total: 'US$635,00', _total: 635 }],
			CLP: [{ total: '$579.120', _total: 579120 }],
		},
	},
	{
		fecvue: '2023/02/20',
		itineravlo:
			'Salida 20 Febrero Santiago-Rio de Janeiro vuelo SKY 620 Sale 05:05 Llega 09:15<br />\nRegreso 01 Marzo Rio de Janeiro-Santiago vuelo SKY 621 Sale 10:05 Llega 14:55',
		pdBaggPersonal: '1',
		pdBaggMano: '0',
		pdBaggBodega: '1',
		diaDesfaseBloq: '0',
		fechaOutBloq: '1900/01/01',
		code: 'PD_BL23RIO06',
		image: 'https://online.panamericanaturismo.cl/public/img/programas/upl_PD_BL23RIO06.jpg',
		city: 'RIO JANEIRO',
		country: 'BRASIL',
		title: 'VERANO EN RIO DE JANEIRO',
		notes:
			'Incluye tasas de embarque USD 41, sujeto a cambio por parte de las autoridades locales.<br />\nServicios de traslados incluidos en servicio compartido. Consultar por precios en privado.<br />\nHabitaciones triples podrían estar compuestas de 2 camas dobles para compartir.',
		description: '',
		epigraph: '',
		coverage: [
			'Pasaje aéreo Santiago/Rio de Janeiro/Santiago vía Sky Airline. Vuelo directo.',
			'Incluye equipaje en bodega',
			'Traslado en servicio compartido aeropuerto / hotel',
			'Noches de alojamiento con desayuno',
			'Asistencia viajes de cortesía',
			'Traslado en servicio compartido hotel / aeropuerto',
			'Tasas de embarque',
			'',
		],
		amenities: {
			hotel: true,
			flight: true,
			transfer: true,
			insurance: true,
			excursion: false,
			food_plan_all: false,
		},
		amount: {
			USD: [{ total: 'US$635,00', _total: 635 }],
			CLP: [{ total: '$579.120', _total: 579120 }],
		},
	},
];
